import type { Repository } from './repository';
import type { CacheInfo, Poi, PoiKind, Station, SyncReport } from './types';
import fountains from './fixtures/fountains.json';
import swimAreas from './fixtures/swim_areas.json';
import coolPlaces from './fixtures/cool_places.json';
import stations from './fixtures/stations.json';
import meta from './fixtures/meta.json';

// Generated by scripts/make-fixtures.mjs. The JSON is typed loosely by the
// compiler (`kind: string`), so cast once here.
const POIS = [...fountains, ...swimAreas, ...coolPlaces] as Poi[];
const STATIONS = stations as Station[];

/** Static data for the browser and for builds without a reachable server. */
export class FixtureRepository implements Repository {
  async cacheInfo(): Promise<CacheInfo> {
    return {
      last_sync_at: meta.generated_at,
      generated_at: meta.generated_at,
      poi_count: POIS.length,
      station_count: STATIONS.length,
    };
  }

  async syncNow(): Promise<SyncReport> {
    return {
      poi_count: POIS.length,
      station_count: STATIONS.length,
      generated_at: meta.generated_at,
    };
  }

  async listPois(kind?: PoiKind): Promise<Poi[]> {
    return kind ? POIS.filter((p) => p.kind === kind) : POIS;
  }

  async listStations(): Promise<Station[]> {
    return STATIONS;
  }
}
